version: 2.1
commands:
  print_pipeline_id:
    parameters:
       id:
         type:string
       steps:
         - run : echo <<parameters.id>>
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -  print_pipeline_id:
           id:<<pipeline.id>>

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
     
